name: Deploy Next.js to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug file structure
        run: ls -R

      - name: Copy source files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          source: "public,src,package.json,package-lock.json,next.config.ts,tsconfig.json,postcss.config.js"
          target: /www/wwwroot/frontend-user

      - name: Build dan Running...
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          command: |
            cd /www/wwwroot/frontend-user
            echo "ğŸ“‚ Sekarang ada di: $(pwd)"

            echo "ğŸ—‘ï¸ Menghapus folder .next lama..."
            rm -rf .next

            echo "ğŸ“¦ Install dependency (production)..."
            npm install --production

            echo "ğŸ—ï¸ Build Next.js..."
            npm run build

            echo "â¹ï¸ Stop PM2 lama..."
            pm2 stop frontend-user || true
            pm2 delete frontend-user || true

            echo "ğŸš€ Start ulang PM2..."
            pm2 start npm --name "frontend-user" -- run start
            pm2 save

            echo "âœ… Deploy selesai!"
